# Generated by Django 5.2 on 2025-09-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
            ],
        ),
    ]
