# Generated by Django 5.2 on 2025-09-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0002_temoignage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRealises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
            ],
        ),
    ]
