# Generated by Django 5.2 on 2025-09-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0003_servicerealises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_footer', models.CharField()),
            ],
        ),
    ]
