# Generated by Django 5.2 on 2025-09-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0004_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='nom_footer',
            new_name='footer',
        ),
    ]
