# Generated by Django 5.2 on 2025-09-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0005_rename_nom_footer_footer_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.CharField(help_text="Classe de l'icone  (ex:'fa-solid fa code')", max_length=100)),
                ('couleur', models.CharField(default='text-blue-500', help_text='Classe Tailwind (ex: text-red-500)', max_length=50)),
                ('lien', models.URLField(blank=True, help_text='Lien ves le service (optionnel)', null=True)),
            ],
        ),
    ]
