# Generated by Django 5.2 on 2025-09-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0006_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='lien',
        ),
        migrations.CreateModel(
            name='DemandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('objectif', models.CharField(blank=True, help_text='but principal du projet', max_length=150)),
                ('message', models.CharField()),
                ('budget_estime', models.CharField(blank=True, max_length=50)),
                ('delai_souhaite', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='briefs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='vortech.service')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
