# Generated by Django 5.2 on 2025-09-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0007_remove_service_lien_demandeservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeservice',
            old_name='Service',
            new_name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
