# Generated by Django 5.2 on 2025-09-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0008_rename_service_demandeservice_service_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeservice',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
