# Generated by Django 5.2 on 2025-09-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0009_demandeservice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeservice',
            name='slug',
        ),
    ]
