# Generated by Django 5.2 on 2025-09-06 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0011_alter_service_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='footer',
            new_name='texte',
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='nom du reseau', max_length=50)),
                ('url', models.URLField(help_text='lien vers le site')),
                ('icone', models.CharField(help_text='classe css FontAwesome, ex: fab fa-facebook', max_length=50)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien', to='vortech.footer')),
            ],
        ),
    ]
