# Generated by Django 5.2 on 2025-09-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0012_rename_footer_footer_texte_footerlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='vortech.footer'),
        ),
    ]
