# Generated by Django 5.2 on 2025-09-06 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vortech', '0013_alter_footerlink_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='vortech.footer'),
        ),
    ]
